### PR TITLE
ARM devtools added databasebackup

### PR DESCRIPTION
**Pull request by microtechno9000**
# Description

Small change to the arm devtools, adding in database backup

Fixes # (issue title here)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.
Please also list any relevant details for your test configuration

- [ ] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] Debian 10
- [ ] Debian 11
- [ ] Docker
- [ ] Other (Please state here)

# Checklist:

- [x] **I have submitted this PR against the `v2_devel` branch (Unless the main branch has a security issue)**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have tested that my fix is effective or that my feature works

### CODE REVIEW

**Review by 1337-server — APPROVED** [review]

**Comment by 1337-server** [comment]
Approved, but you will need to update your submodule before we can merge

**Comment by microtechno9000** [comment]
@1337-server submodules updated

**Comment by 1337-server** [comment]
Still showing conflicts `arm-dependencies`

**Comment by 1337-server** [comment]
Your arm deps tagged at: 96cf0745491a58e4df9328a87a1de1847bbc0ce0 - https://github.com/automatic-ripping-machine/arm-dependencies/tree/96cf0745491a58e4df9328a87a1de1847bbc0ce0

Main deps tagged at:9c0d7b989b76f8a2fe9a2ff3ce45e19836d05f62 - https://github.com/automatic-ripping-machine/arm-dependencies/tree/9c0d7b989b76f8a2fe9a2ff3ce45e19836d05f62

**Comment by microtechno9000** [comment]
Updated, my fork was out of date
With all the changes you both have made it was a little out of date, it should be good now. I don't see any conflicts

**Pull request merged**
