### PR TITLE
Add configurable URL for notifications

### PR DESCRIPTION
**Pull request by anthonylavado**
# Description
In #949, a user proposes adding a configurable field that would be used for notifications. This adds a field called `UI_BASE_URL` for that purpose.

Fixes # 949

## Type of change
Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

- [x] Docker

I get notifications through Telegram, and I have all my containers behind a reverse proxy (Caddy) for ease of access at home. With this in place and configured, the notification URL brings me directly to the ARM page to review the job.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have tested that my fix is effective or that my feature works

# Changelog:

Include the details of changes made here
- Add UI_BASE_URL to arm.yaml, for setting a display address in notifications

# Logs
Full logs can be provided, but here's an example of the result:
image

# Notes

I can add documentation if required.

I have not added any type of input validation on this field, but it would clearly be suited to entering a protocol and hostname. An enhancement would be to add two extra items:
1. If no protocol is entered, automatically append "http://" to the beginning of the field's contents
2. (Maybe) perform filtering to ensure only a hostname is entered, not spurious text
These could likely be both satisfied by implementing [urllib.parse](https://docs.python.org/3.0/library/urllib.parse.html).

### CODE REVIEW

**Comment by anthonylavado** [comment]
The SonarCloud fail is kind of funny actually, since it already had http in the original notification, I just moved it around.

Forgot to mention - I'm open to changing the name if anyone has a better suggestion. The only one I could think of was `display_address` which is what I use in the code itself. This was also my first time working with Alembic, so I'm also open to adding any documentation you want around that (to [here](https://github.com/automatic-ripping-machine/automatic-ripping-machine/tree/main/arm/migrations)).

**Comment by microtechno9000** [comment]
@anthonylavado can you add a comment/close the sonarlint review. Had a look and it is just around http vs https. ARM isn't using https so no issues, can mark the security issue as closed/safe. Doesn't look like I can do that.

**Comment by anthonylavado** [comment]
@microtechno9000 It doesn't look like I can change it either. It might only be set up to allow Wolfy to do so.

I'll fix the merge conflict before we tag him.

**Comment by 1337-server** [comment]
The issue should now be ok. I marked it as safe.

**Comment by microtechno9000** [comment]
> @microtechno9000 It doesn't look like I can change it either. It might only be set up to allow Wolfy to do so.
> 
> I'll fix the merge conflict before we tag him.

once the merge conflict is resolved, I can review and close. No issues with the modification

**Comment by anthonylavado** [comment]
I think I've pulled in the changes to models and fixed it, but it looks like a right mess. I'm just building locally to test and make sure it still works.

**Comment by anthonylavado** [comment]
Looks like we're good. Thanks all!

**Review by microtechno9000 — APPROVED** [review]

**Pull request merged**
