### PR TITLE
Fix sed delimiter error

### LINKED ISSUE #587: can't get to setup page on auto installer on 20.04
- [X] I have checked the wiki
- [X] I have searched for similar issues

**Describe the bug**
First-time setup never launches when running automatic setup.

**To Reproduce**
1. Follow instructions for automatic setup for Ubuntu 20.04
2. First time setup never launches
3. Manually loading http://[ip]:8080/setup in the browser results in "Unable to connect Firefox can’t establish a connection to the server"

### Environment
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.5 LTS"

arm@fireflash:/opt/arm$ git branch
* (no branch)
arm@fireflash:/opt/arm$ git log -1
commit 66b784e95437ab38e81425ce06f86f7e9afcc578 (HEAD, tag: v2.6.7, origin/v2_devel)
Author: wolfy <wolfy@shitwolfymakes.com>
Date:   Mon Sep 26 23:58:18 2022 -0600

    dev branch now properly checked out during clone (#580)

There doesn't appear to be any errors in the console when installing.  A few warnings like the following:

WARNING: The script apprise is installed in '/home/arm/.local/bin' which is not on PATH.

### PR DESCRIPTION
**Pull request by Zackptg5**
# Description

Fixes sed delimiter error

Fixes #587

## Type of change

Please delete options that are not relevant.

- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.
Please also list any relevant details for your test configuration

- [X] Docker

### CODE REVIEW

**Comment by shitwolfymakes** [comment]
Didn't see this when I was replying to #598.

Please include a log confirming this does not cause a breaking change when run on Ubuntu Desktop 20.04, and I will happily merge this.

**Comment by Zackptg5** [comment]
What kind of long do you want? This is just the initial setup script before arm even runs. It's just a syntax error in the sed statment

**Comment by shitwolfymakes** [comment]
Belay that. My editor never saved the changes I was testing. I've confirmed this is working, will review in a moment

**Review by shitwolfymakes — APPROVED** [review]
Nice catch!

**Pull request merged**
