### PR TITLE
Added basic webserver for status

### PR DESCRIPTION
**Pull request by audioeng**
I have parameterized the script I mentioned in #87 , pulling the path variables from config file to establish paths. This uses os.statvfs which will not work on WIndows. I believe this is the only limitation.
I also added Disk Info about the ARMPATH as well as RAWPATH as you can see in my screenshots below.

Please try this out, put this python file in your ARM directory and use as follows.
I am expecting some folks to test before adding this in. Right now the script must be run manually, which is good for this testing phase I think.

```
Very basic web access to log and queue monitor for ARM (Automatic Ripping Machine) https://github.com/ahnooie/automatic-ripping-machine


Usage::
    Place script in /opt/arm directory 
    sudo ./logserve.py [<port>]

View the empty.log in reverse order::
    http://localhost:[port]
    
View the Info page
    http://localhost:[port]/info/
```

Screenshot of empty.log in browser: (must manually reload)
screen shot 2017-09-23 at 10 41 37 pm

Screenshot of Info page in browser: (refreshes every 60 seconds)
screen shot 2017-09-23 at 11 20 53 pm

### CODE REVIEW

**Comment by audioeng** [comment]
Here are some updated screenshots since I updated the script to do some sorting and made the Log load much different/faster.
screen shot 2017-10-03 at 7 41 39 pm
screen shot 2017-10-03 at 7 42 10 pm

**Comment by frankcharlton** [comment]
This is failing for me:
sudo ./logserve.py 8000
  File "./logserve.py", line 33
    def getsize(path)
                    ^
SyntaxError: invalid syntax

I've tried hardcoding the paths to see if that helped, and it didn't :)

Any ideas?

**Comment by audioeng** [comment]
Thanks Frank,

Yes, complete syntax boo-boo.

I forgot the `:` at the end of `def getsize(path)`
I have just changed and committed that.

**Comment by muckngrind4** [comment]
This is nice @audioeng.  I've merged it into a branch I'm working on (v2_master), made a couple changes to run on Python 3 and have it working.

Thanks!

**Comment by audioeng** [comment]
Oh cool, I’ll check out your branch, I am all for it running in python 3.x

**Comment by muckngrind4** [comment]
This was manually pulled into v2 so I'm going to close it.

**Pull request closed without merging**
