### PR TITLE
V2.1 dev

### PR DESCRIPTION
**Pull request by flammableliquids**
Everyone is using v2.1_dev. 
The master is almost useless.
This will probably create more bug reports, but it's best to remove the deadwood and move forward.
Creating new milestone

### CODE REVIEW

**Comment by microtechno9000** [comment]
Can this branch be merged with the master/main, it has the most features and without the merge any other pull requests are blocked

**Comment by 1337-server** [comment]
Any update on this ?

**Comment by MrTechGadget** [comment]
Sounds like we are in favor of this but there are some merge conflicts to deal with first.

**Comment by 1337-server** [comment]
I'm not able to do anything as I only have read access.

**Pull request merged**
