### PR TITLE
implement forkawesome iconography

### PR DESCRIPTION
**Pull request by newhinton**
# Description
Implements Forkawesome iconography.

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Manual Review with dev-setup.

# Checklist:

- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have tested that my fix is effective or that my feature works

# Changelog:

Include the details of changes made here
- Add Forkawesome to css folder
- Replace multiple old icons with ones from forkawesome

# Logs
Attach logs from successful test runs here

### CODE REVIEW

**Comment by newhinton** [comment]
Full width:
image

Smaller:
image

Settingspages:

image

**Comment by microtechno9000** [comment]
Any change to the notifications?

**Comment by newhinton** [comment]
No, not that i know of.
But i want to improve on then in a later pr

**Comment by shitwolfymakes** [comment]
Please fix the merge conflicts, then ping me in discord when it's ready to be reviewed!

**Comment by newhinton** [comment]
Due to @1337-server's work in https://github.com/automatic-ripping-machine/automatic-ripping-machine/tree/arm-vuejs i think this is not wise to be merged. It will only be removed when that branch is done.

**Pull request closed without merging**
