### PR TITLE
[MAJOR] ARM UI Rewrite, Split and Docker-Compose

### PR DESCRIPTION
**Pull request by microtechno9000**
# Description
Major rewrite of the ARM UI code to allow for separation of the ripper, UI and into separate docker images.
There are a lot of structural changes in this PR, which unfortunately due to the way ARM has been designed to date required a lot of work, hence the monolithic PR.
**Note:** This PR breaks a lot of ARM, see below for known issues

_Updates_
- ARM Models separated to only be database models
- UI rewritten to align the Flask structure with an easier to define template
  - Flask configuration now allows for Development, Production and Testing configurations
  - Starting Flask calls less dependencies, only those required within Flask (smaller container)
  - Starting the ripper, will no longer pull in the Flask UI (via Models)
- Docker, moved to docker-compose
- Separate ARM UI docker compose container built
- Database migrated from sqlite to MySQL

_New Featuress_
- ARM UI on start allows users to add in their own system configuration settings and info (UI only, at present)
- Import database data from arm.db into the MySQL database (known issues), currently there just for testing
- Addition of Unit Testing for UI (partial)

_Known Issues_
- A lot of unused functions and calls 'commented out', require migrating into the ripper
- A lot of debugging of the UI was conducted; however, due to the rewrite, there may be UI functions that don't work (or as per above, expect some ripper code to work)
- UI still requires access to volumes and devices to maintain some functions. This is work to go to remove
- RIPPER DOES NOT WORK, she be well broke!
- Unit testing started, but not fully implemented, with later code changes the unit testing broke
- Sonarcloud has thrown a lot of errors with the 'new' code, which is old code but shifted. Work is still required to bring this up to scratch and make it A class code
- Migrating the database doesn't check for existing jobs, so users could create multiple duplicates with no error checking.

## Type of change
Please delete options that are not relevant.

- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.
Please also list any relevant details for your test configuration

Details on how to setup and run ARM v3.x are captured in the amended
- README
- Status-Roadmap.md
- Development-Branch.md

- [x] Docker
- [x] PyCharm

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have tested that my fix is effective or that my feature works

# Changelog:
Where to start!

 1. Rewrite of ARM UI code
    - [x] Refactor to Flask Factory
    - [x] Refactor Models to remove links to ripper code
       - [x] Models refactor
       - [x] Models Unit Test
    - [ ] Models - remove UI and Ripper dependency to models
    - [x] Config - de-tangle integration
    - [x] Refactor Blueprints to align with Models
    - [ ] Add Unit Testing in for UI pages and key functions
      - completed in part
    - Code cleanup
      - [ ] Remove ui/utils, once code moved out

2. Move from docker to docker-compose
   - [x] Implemented, docker-compose.yml created and configured
   - [x] Create separate ARM DB Container
   - [ ] Create separate ARM Ripper Container
   - [x] Create separate ARM UI Container

3. Move the database from SQLite to MySQL
   - [x] Create MySQL container
   - [x] Migrate ARM UI
   - [ ] Migrate ARM Ripper

# Logs
Attach logs from successful test runs here

## Docker

```bash
docker ps
CONTAINER ID   IMAGE                                                   COMMAND                  CREATED          STATUS                            PORTS                                                  NAMES
914d7e03b1bf   automaticrippingmachine/automatic-ripping-machine:3.0   "/sbin/my_init"          4 minutes ago    Up 4 minutes (health: starting)   0.0.0.0:8080->8080/tcp, :::8080->8080/tcp              automatic-ripping-machine_arm-main_1
58880a91d50a   mysql:latest                                            "docker-entrypoint.s…"   18 minutes ago   Up 4 minutes                      0.0.0.0:3306->3306/tcp, :::3306->3306/tcp, 33060/tcp   arm-db
```
```bash
docker image list
REPOSITORY                                          TAG           IMAGE ID       CREATED         SIZE
automaticrippingmachine/automatic-ripping-machine   3.0           c55a1dae86a7   4 minutes ago   1.13GB
```

docker build logs
[3_0_dev_dockerbuild.txt](https://github.com/user-attachments/files/16917645/3_0_dev_dockerbuild.txt)

features
- ARM UI System Info on start
- ARM Database Migration

arm_ui_server

arm_ui_migrate

### CODE REVIEW

**Review by shitwolfymakes — CHANGES_REQUESTED** [review]
Make sure the version of the `mysql` image is pinned and not `latest`

**Comment by microtechno9000** [comment]
> Make sure the version of the `mysql` image is pinned and not `latest`

updated

**Comment by microtechno9000** [comment]
Fixed MySQL, the 9.0.1 didn't work, 8.3.0 is the latest

```bash
$ docker ps
CONTAINER ID   IMAGE                                                   COMMAND                  CREATED          STATUS                             PORTS                                                  NAMES
5b6d08c44efc   mysql:8.3.0                                             "docker-entrypoint.s…"   3 minutes ago    Up 3 minutes                       0.0.0.0:3306->3306/tcp, :::3306->3306/tcp, 33060/tcp   arm-db
aecf373a6743   automaticrippingmachine/automatic-ripping-machine:3.0   "/sbin/my_init"          13 minutes ago   Up 13 minutes (health: starting)   0.0.0.0:8080->8080/tcp, :::8080->8080/tcp              automatic-ripping-machine_arm-main_1
```

**Comment by microtechno9000** [comment]
updated the base image to jammy and removed some of the dependencies for the arm-ui image

image size reduced
from: 1.13 GB
to: 997 MB

```bash
$ docker image ls
REPOSITORY                       TAG           IMAGE ID       CREATED         SIZE
automaticrippingmachine/arm-ui   3.0.0_dev     877c26edecd2   2 hours ago     997MB
```

**Comment by microtechno9000** [comment]
> Looks great so far! Is there any reason to use Oracles MySQL instead of MariaDB? IMHO MariaDB would probably much more align with the values of this project.
> `mariadb:lts-noble` should be a good starting point. There are differences between MariaDB and Oracle MySQL, we would have to see if those are relevant.

Only because I havent used any other, and SQLAlchemy works with MySQL.
if there is no difference and a benefit to using MariaDB, send through some info and I can have a look.
I am about to merge this PR into the dev branch, so raise a discussion or send on Discord.

**Pull request merged**
