### PR TITLE
Ntfy and Bash for notifications

### LINKED ISSUE #924: 🔧 Support for ntfy
### Is this feature missing in the latest version?

- [X] I'm using the latest release

### Is your feature request related to a problem? Please describe.

I would like to recieve notifications via ntfy.

https://github.com/caronc/apprise/wiki/Notify_ntfy
It is supported by apprise.

### Describe the solution you'd like?

Se above.

### Describe alternatives you've considered?

_No response_

### Anything else?

Thanks for your work!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by newhinton**
# Description
This allows the user to use Ntfy.sh for notifications.
It also allows the user to use a generic bash script to be called for notifications allowing even more flexibility.
I included a tiny test-script that allows any developer to execute the notification stack without a full working arm-stack.

Fixes #924

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] This change requires a documentation update

# How Has This Been Tested?
Via the provided Test-Script and my own test instance.

- [ ] Docker
- [x] Other (See above)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have tested that my fix is effective or that my feature works

# Changelog:

Include the details of changes made here
- Add ntfy as a notification target
- Add bash as a notification target

# Logs
None

### CODE REVIEW

**Comment by shitwolfymakes** [comment]
Please fix the merge conflicts, then ping me in discord when it's ready to be reviewed!

**Comment by microtechno9000** [comment]
can you fix the quality checks for ARM 3.10

**Comment by newhinton** [comment]
@microtechno9000 They complain about the function beeing to long.

I can just make multiple functions out of that one, but i am not sure if the function itself is wanted since i basically transplanted code from a branch ~6 month ago into the current one. 

As far as i can see, each provider allows only for a single combination of tokens and settings with all beeing more or less mandatory, however mine allows multiple. 

And bash is completely different again since it doesn't call apprise but a subprocess. Could you take a look at it if this is the wanted structure to keep it maintainable for the future?

**Comment by newhinton** [comment]
@microtechno9000 Done!

**Comment by shitwolfymakes** [comment]
Is this ready for review?

**Comment by newhinton** [comment]
Yes!

**Review by shitwolfymakes — APPROVED** [review]

**Pull request merged**
