### PR TITLE
Pr flask sqlalchemy 3 support

### PR DESCRIPTION
**Pull request by 1337-server**
# Description
These are the changes required to update all the dependencies from requirement.txt

## Type of change
Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.
Please also list any relevant details for your test configuration.

- [x] Docker
- [x] Other (Please state here)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have tested that my fix is effective or that my feature works

# Changelog:

Include the details of changes made here
- Add support for flask-sqlalchemy 3+

# Logs
Attach logs from successful test runs here

### CODE REVIEW

**Comment by microtechno9000** [comment]
Running this in docker using an old database that needs migration caused the docker container to fail and drop the connection/web page

**Comment by 1337-server** [comment]
Tested with local build using local build of https://github.com/automatic-ripping-machine/arm-dependencies/pull/189 as the base

Log files:
- Audio disc - [Audio-cd.zip](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/12021297/Audio-cd.zip)
- MakeMKV -> HandBrake - [MakeMKV-HandBrake.zip](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/12021298/MakeMKV-HandBrake.zip) (`RIPMETHOD: mkv`)
- Handbrake only - [HandBrake-only.zip](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/12021299/HandBrake-only.zip) (`RIPMETHOD: backup`)

**Comment by 1337-server** [comment]
> Running this in docker using an old database that needs migration caused the docker container to fail and drop the connection/web page '/dbupdate'
> 
> ```
> [2023-04-21 12:47:31,685] DEBUG ARM: database.update_database User requested - Database migration
> [2023-04-21 12:47:31,688] DEBUG ARM: utils.arm_alembic_get Alembic Head is: 95623e8c5d58
> [2023-04-21 12:47:31,689] DEBUG ARM: utils.arm_db_get Database Head is: 2e0dc31fcb2e
> [2023-04-21 12:47:31,689] INFO ARM: utils.arm_db_migrate Database out of date. Head is 95623e8c5d58 and database is 2e0dc31fcb2e. Upgrading database...
> [2023-04-21 12:47:31,689] INFO ARM: utils.arm_db_migrate Backing up database '/home/arm/db/arm.db' to '/home/arm/db/arm.db_migration_2023-04-21_1247'.
> [2023-04-21 12:47:38,248] DEBUG ARM: utils.arm_alembic_get Alembic Head is: 95623e8c5d58
> [2023-04-21 12:47:38,249] DEBUG ARM: utils.arm_db_get Database Head is: 2e0dc31fcb2e
> [2023-04-21 12:47:38,249] INFO ARM: utils.arm_db_check Database is not current, update required. Head: 95623e8c5d58 DB: 2e0dc31fcb2e
> ```

It seems to work with the latest versions I posted (Tested with an older db version from my NAS), however you need to restart the container after updating/migrating the db.

**Comment by shitwolfymakes** [comment]
> Running this in docker using an old database that needs migration caused the docker container to fail and drop the connection/web page '/dbupdate'
> 
> ```
> [2023-04-21 12:47:31,685] DEBUG ARM: database.update_database User requested - Database migration
> [2023-04-21 12:47:31,688] DEBUG ARM: utils.arm_alembic_get Alembic Head is: 95623e8c5d58
> [2023-04-21 12:47:31,689] DEBUG ARM: utils.arm_db_get Database Head is: 2e0dc31fcb2e
> [2023-04-21 12:47:31,689] INFO ARM: utils.arm_db_migrate Database out of date. Head is 95623e8c5d58 and database is 2e0dc31fcb2e. Upgrading database...
> [2023-04-21 12:47:31,689] INFO ARM: utils.arm_db_migrate Backing up database '/home/arm/db/arm.db' to '/home/arm/db/arm.db_migration_2023-04-21_1247'.
> [2023-04-21 12:47:38,248] DEBUG ARM: utils.arm_alembic_get Alembic Head is: 95623e8c5d58
> [2023-04-21 12:47:38,249] DEBUG ARM: utils.arm_db_get Database Head is: 2e0dc31fcb2e
> [2023-04-21 12:47:38,249] INFO ARM: utils.arm_db_check Database is not current, update required. Head: 95623e8c5d58 DB: 2e0dc31fcb2e
> ```

@microtechno9000 Has this been fixed with the latest commits?

**Comment by 1337-server** [comment]
> > Running this in docker using an old database that needs migration caused the docker container to fail and drop the connection/web page '/dbupdate'
> > ```
> > [2023-04-21 12:47:31,685] DEBUG ARM: database.update_database User requested - Database migration
> > [2023-04-21 12:47:31,688] DEBUG ARM: utils.arm_alembic_get Alembic Head is: 95623e8c5d58
> > [2023-04-21 12:47:31,689] DEBUG ARM: utils.arm_db_get Database Head is: 2e0dc31fcb2e
> > [2023-04-21 12:47:31,689] INFO ARM: utils.arm_db_migrate Database out of date. Head is 95623e8c5d58 and database is 2e0dc31fcb2e. Upgrading database...
> > [2023-04-21 12:47:31,689] INFO ARM: utils.arm_db_migrate Backing up database '/home/arm/db/arm.db' to '/home/arm/db/arm.db_migration_2023-04-21_1247'.
> > [2023-04-21 12:47:38,248] DEBUG ARM: utils.arm_alembic_get Alembic Head is: 95623e8c5d58
> > [2023-04-21 12:47:38,249] DEBUG ARM: utils.arm_db_get Database Head is: 2e0dc31fcb2e
> > [2023-04-21 12:47:38,249] INFO ARM: utils.arm_db_check Database is not current, update required. Head: 95623e8c5d58 DB: 2e0dc31fcb2e
> > ```
> 
> @microtechno9000 Has this been fixed with the latest commits?

It seems like because of the new global config changes, the config isn't updated after upgrading the database ? I just had a casual look, but I think that might be the issue. Restarting the container fixed the issue.
This isn't great for long term, but I don't think this PR is the issue.

**Comment by shitwolfymakes** [comment]
What steps fix this? I want to hold off on merging until we have a solution.

**Comment by 1337-server** [comment]
Not sure yet, but It's because after migrating the main armui_cfg is never fully updated as it only runs once on first start up.

https://github.com/automatic-ripping-machine/automatic-ripping-machine/blob/7f3ed593c0c261dded7e122366df2ccd03685661/arm/ui/routes.py#L31

And even though it gets updated after the migrate it doesn't stick to the global armui_cfg

**Comment by 1337-server** [comment]
Latest commit fixes the issue.

**Review by shitwolfymakes — APPROVED** [review]

**Pull request merged**
