### PR TITLE
Adds optional config file locations

### PR DESCRIPTION
**Pull request by NickHastings**
# Description

This PR allows the user to choose between three options for the arm.yaml config file. `arm/config/config.py` first tries reading the config from `~/.config/arm/arm.yaml`, then `/etc/arm/arm.yaml` before finally falling back to the `arm.yaml` in the source directory.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

I've used this by running the ripper and the armui with the config `/etc/arm/arm.yaml` and another time in `/home/arm/.config/arm.yaml`.

Interestingly, arm_wrapper.sh expects the config to be in `/etc/arm` whereas the existing python code expects it to be in the source tree. I have a modified version of arm_wrapper.sh that searches the same paths as this updated `config.py`, but it has additional features, so that will be in a separate PR.

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Debian 10
- [x] Debian 11
- [ ] Docker
- [ ] Other (Please state here)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
      The changes are very minor, and I think it is clear what code is doing
      without explicit comments.
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have tested that my fix is effective or that my feature works

### CODE REVIEW

**Comment by 1337-server** [comment]
This conflicts a little with 1337-server/automatic-ripping-machine#179

**Comment by NickHastings** [comment]
> This conflicts a little with [1337-server#179](https://github.com/1337-server/automatic-ripping-machine/pull/179)

Hmm, it does. What if I wait until you get [1337-server#179](https://github.com/1337-server/automatic-ripping-machine/pull/179) merged, and then I reimplement this feature?

**Comment by 1337-server** [comment]
Yeah, that would be fine. I'm not sure on the planned date for merging it into the main repo though.

**Comment by NickHastings** [comment]
@1337-server so in general pull requests should be against the v2_devel branch?

**Comment by 1337-server** [comment]
Yes. The v2_devel branch is the latest version that will eventually get merged into v2_master.

But we have the devel branch to allow more testing of the new features, without annoying users who just want it to work without issues.

**Pull request closed without merging**
