### PR TITLE
Added experimental Auto grabbing of MakeMKV beta keys + double rip prevention.

### PR DESCRIPTION
**Pull request by duplexsystem**
MakeMKV auto grabbing Still needs some work:
- Option to enable / disable needs to be moved to config file.
- Might mess up during times when there are two rips taking place at the same time (need to add fail safe)
- Overwrites MakeMKV config file in stead of changing it
- If key grab fails will still overwrite MakeMKV config file with blank of blotched key.
Fixed double ripping #113

### CODE REVIEW

**Comment by muckngrind4** [comment]
Hi @budgidiere, I just created a v2.1_dev branch and I'll likely merge this into that branch tomorrow.  I'm trying to stabalize v2_master for a release.  Thanks for the contribution!

**Comment by aron7676** [comment]
Suggestion, make the pickle data a tuple, with (discdrive, str(disc.videotitle)) as the data. 
ex (sr0, avatar)
on script start, check if pickle[0] = disc and pickle[1] = title. 
Should fix the issue, just dont have the time to do the fork, update/test code/ push.

**Comment by 1337-server** [comment]
No longer needed as MakeMKV already handles this.

**Comment by duplexsystem** [comment]
#192 should be reopened then

**Comment by 1337-server** [comment]
Part of #113 is taken care of with this #294 (Stop Drive door from auto closing)


The rest such as dupe rip protection are here
-------------------
This version kills instant duplicate rips - When the udev triggers twice quickly (<1 mins on the same devpath (/dev/sr0))
https://github.com/automatic-ripping-machine/automatic-ripping-machine/blob/cc52f90e991047ddd6ab4e1b024d2ebf795ae063/arm/ripper/main.py#L405


This version stops jobs that are already in the transcoding path
-------------------
https://github.com/automatic-ripping-machine/automatic-ripping-machine/blob/cc52f90e991047ddd6ab4e1b024d2ebf795ae063/arm/ripper/main.py#L217



But in the more updated v2_devel branch of ARM, there is a more complicated version of the have dupes check here
-------------------
https://github.com/automatic-ripping-machine/automatic-ripping-machine/blob/158dc70a01635c63c062738877be8a03470eff6c/arm/ripper/main.py#L179
which triggers this
https://github.com/automatic-ripping-machine/automatic-ripping-machine/blob/158dc70a01635c63c062738877be8a03470eff6c/arm/ripper/utils.py#L543


I'm sure this will cover most cases, and adding more checks on top of these already excessive check is unnecessary I think.

**Pull request closed without merging**
