### PR TITLE
Add Apprise notifications

### PR DESCRIPTION
**Pull request by 1337-server**
Only the arm.yaml.sample and utils.py need updated for apprise notifications.

All the other changes are either debian focused or small fixes and one to send identified media to the media folder instead of the unidentifed folder.
EDIT: 
I didnt include the update to the requirments.txt

You will need to install it via `pip install apprise`

### CODE REVIEW

**Comment by flammableliquids** [comment]
@1337-server A lot of stuff you have done is really great.
At a quick glance the installation files look epic, and that you set up the ui as a service, is something classy, (It annoyed me that I had to insert a disk, but not enough to do anything about it). 
It would be nice to merge into the master. Why have you chosen v2.1_dev?

**Comment by 1337-server** [comment]
> @1337-server A lot of stuff you have done is really great.
> At a quick glance the installation files look epic, and that you set up the ui as a service, is something classy, (It annoyed me that I had to insert a disk, but not enough to do anything about it).
> It would be nice to merge into the master. Why have you chosen v2.1_dev?

I just assumed the dev 2.1 branch was still the main dev branch and would be ahead in commits, and i didnt check this.

**Comment by flammableliquids** [comment]
> 
> 
> > @1337-server A lot of stuff you have done is really great.
> > At a quick glance the installation files look epic, and that you set up the ui as a service, is something classy, (It annoyed me that I had to insert a disk, but not enough to do anything about it).
> > It would be nice to merge into the master. Why have you chosen v2.1_dev?
> 
> I just assumed the dev 2.1 branch was still the main dev branch and would be ahead in commits, and i didnt check this.

**Comment by flammableliquids** [comment]
> 
> 
> > > @1337-server A lot of stuff you have done is really great.
> > > At a quick glance the installation files look epic, and that you set up the ui as a service, is something classy, (It annoyed me that I had to insert a disk, but not enough to do anything about it).
> > > It would be nice to merge into the master. Why have you chosen v2.1_dev?
> > 
> > 
> > I just assumed the dev 2.1 branch was still the main dev branch and would be ahead in commits, and i didnt check this.

Have a think about what you want to do. 
I accidentally clicked close, I have re-opened it so that you can either cancel it and bring up to speed to the master, or if you want, commit to 2.1_dev. (I would prefer not to do this as it would be hard to merge back to the master).

**Comment by 1337-server** [comment]
> > > > @1337-server A lot of stuff you have done is really great.
> > > > At a quick glance the installation files look epic, and that you set up the ui as a service, is something classy, (It annoyed me that I had to insert a disk, but not enough to do anything about it).
> > > > It would be nice to merge into the master. Why have you chosen v2.1_dev?
> > > 
> > > 
> > > I just assumed the dev 2.1 branch was still the main dev branch and would be ahead in commits, and i didnt check this.
> 
> Have a think about what you want to do.
> I accidentally clicked close, I have re-opened it so that you can either cancel it and bring up to speed to the master, or if you want, commit to 2.1_dev. (I would prefer not to do this as it would be hard to merge back to the master).

Ill go over the differences from 2.1 and master so they can be committed easier

**Pull request closed without merging**
