### PR TITLE
Fix permissions issue caused by a8a8b8f

### PR DESCRIPTION
**Pull request by shitwolfymakes**
# Description
Fixed an issue created by removing permissions setting in commit a8a8b8f. Confirmed working after running the rebuilt container.

The wiki now includes a note about default permissions for newly created folders and how that make affects users on mounting file shares

## Type of change
Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.
Please also list any relevant details for your test configuration

- [x] Docker

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have tested that my fix is effective or that my feature works

### CODE REVIEW

**Comment by shitwolfymakes** [comment]
@SylvainMT This will fix your issue once merged and released

**Review by microtechno9000 — COMMENTED** [review]
Agree with the fix, seems the removal of chown to resolve a specific issue was not worth the general hassle.

Can you amend the wiki to explain that the default behaviour sets the user ARM as the owner using chown. 

There are users that have mounted the ARM folders via a samba or NFS share that this will cause issues. Need to make sure those users are aware and mounting network shares is not the preferred config.

**Comment by shitwolfymakes** [comment]
I see what you mean now. The way this is fixing the permissions issue will break permissions for shares every time it boots. I'll figure out a different way to fix this.

**Comment by shitwolfymakes** [comment]
@SylvainMT This will no longer automatically fix your issue. If you are not using an external share for the container, running this should fix the permissions issues:
```
sudo chown -R arm:arm /home/arm
```

**Review by microtechno9000 — APPROVED** [review]
good with the proposed changes, best of both worlds

**Comment by SylvainMT** [comment]
I also agree, that permissions need only be set at folder creation, not every time the container starts.  Thanks for looking into the issue :)

**Pull request merged**
