### PR TITLE
Fix race condition with certain drives and certain disks

### PR DESCRIPTION
**Pull request by hey-look-a-throwaway**
# Description

Noticed that with an external drive (an external LG SP80NB80) and certain disks (maddening!), there would be a race condition with the drive being ready. Adding a few retries and moving the abort check before we create the `Job()` fixed it on my machine.

```
Fri Apr 19 01:38:56 UTC 2024 Entering docker wrapper
Fri Apr 19 01:38:56 UTC 2024 [ARM] Starting ARM for DVD on sr1
[2024-04-19 01:38:57,689] INFO ARM: main.<module> Drive appears to be empty or is not ready.  Exiting ARM.
```

If I added the retries where the old "Drive appears to be empty" check was, it would bail at `ARM is trying to write a job to the empty.log, or NAS**.log`, so I moved it before.

Anyway, not sure if this is the appropriate place to put this (maybe the issue is with that wrapper?), but it fixed it for me.

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?
It didn't work with some disks (seemed like dual layer ones?), and it does now

- [X] Docker

# Checklist:

- [ ] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [X] I have tested that my fix is effective or that my feature works

# Changelog:

- Add retries for drive being ready before creating the `Job` object
- Move the final drive readyness check as well so that it aborts if it never gets ready

# Logs
Attach logs from successful test runs here

```
Fri Apr 19 02:29:44 UTC 2024 Entering docker wrapper
Fri Apr 19 02:29:44 UTC 2024 [ARM] Starting ARM for DVD on sr1
[2024-04-19 02:29:44,897] INFO ARM: main.<module> Drive appears to be empty or is not ready.  Waiting 1s
[2024-04-19 02:29:45,923] INFO ARM: main.<module> Drive appears to be empty or is not ready.  Waiting 1s
```

### CODE REVIEW

**Comment by microtechno9000** [comment]
Nice fix
can you provide a log of the error pre fix for comparison

**Comment by hey-look-a-throwaway** [comment]
The first code snippet is the befeore log

```
Fri Apr 19 01:38:56 UTC 2024 Entering docker wrapper
Fri Apr 19 01:38:56 UTC 2024 [ARM] Starting ARM for DVD on sr1
[2024-04-19 01:38:57,689] INFO ARM: main.<module> Drive appears to be empty or is not ready.  Exiting ARM.
```

**Comment by microtechno9000** [comment]
Cheers
Had in my head the code was in a loop, not failing due to states.

Good fix, only suggestion would be to amend the INFO statement to state something like [attempt x of n], otherwise users may see the line multiple times in the log and think there is another issue. Once you have added that, good to approve.

**Comment by shitwolfymakes** [comment]
> Cheers Had in my head the code was in a loop, not failing due to states.
> 
> Good fix, only suggestion would be to amend the INFO statement to state something like [attempt x of n], otherwise users may see the line multiple times in the log and think there is another issue. Once you have added that, good to approve.

Seconding this, better logging will be great

**Review by microtechno9000 — APPROVED** [review]
good fix, added in the x of y run numbers to provide more information to the end user

**Pull request merged**
