### PR TITLE
#66 Setup a VirtualBox machine with Vagrant and Ansible

### PR DESCRIPTION
**Pull request by jswetzen**
With this in place, `vagrant up` will setup a VirtualBox machine running ARM. Turn off the box with `vagrant halt`, add the physical disk drive to the machine in the VirtualBox GUI and start the machine again. Done! A cifs mount can be added in the machine by setting the appropriate values in the config file `config` (config.sample is copied if it's missing).

### CODE REVIEW

**Comment by ahnooie** [comment]
Thanks @jswetzen , the vagrant and ansible file are fantastic.  One question for you, is it better to store the ansible playbook here with the repo, or should it be an ansible role in it's own repository so that it can be published to ansible-galaxy?  I'm not too familiar with how other projects do this so let me know your thoughts and I'll either pull it in as is or we can discuss further.

**Comment by jswetzen** [comment]
I didn't even think about ansible-galaxy, because I've only worked with private roles before. But that's probably a good idea! I'll look into that and add something to the README about vagrant installation.

**Comment by ahnooie** [comment]
Here's an ansible role I built if you want to use it as a reference, https://github.com/ahnooie/ansible-role-lxd-container (published to galaxy with no issues).  `# ansible-galaxy init rolename` will generate the folder structure and readme templates and such.  If you decide to go that route your playbook in the ARM repo would just be a few lines to include your role.  But if you want I can merge your playbook in now and then change it to use your role once you get it published.

**Comment by jswetzen** [comment]
Ansible-galaxy sounds like a good option. Give me a while and I'll come
back when I've got it published.

lör 29 juli 2017 kl. 09:03 skrev Benjamin Bryan <notifications@github.com>:

**Comment by jswetzen** [comment]
At long last I've got this uploaded to Ansible Galaxy. I also got it updated to match the new install instructions with systemd.

**Comment by emmakat** [comment]
do you have any updated instructions for using this iwth ansible? I'm new to ansible (have used chef), appreciate any simple instructions to try. I have ubuntu server 16.04 LTS.

**Comment by jswetzen** [comment]
Now this PR is updated and can be merged if you want it @ahnooie.

@emmakat if this gets merged, instructions for setting up a Vagrant machine will be in the README. If you want to use it now, you can download the ´vagrant-setup´ branch of my repo and look at the [README](https://github.com/jswetzen/automatic-ripping-machine/tree/vagrant-setup#automated-virtual-machine-setup) there.

**Comment by 1337-server** [comment]
Closing as this is now stale with no updates.

**Pull request closed without merging**
